services:
  app:
    build: .
    container_name: tracker-app
    ports:
      - "8060:8060"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - TZ=America/Denver
    restart: unless-stopped
